services:
  - type: web
    name: appnutri-fe
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_fastapi:app --host 0.0.0.0 --port 10000
    envVars:
      - key: FLET_STATIC_ROOT_DIR
        value: assets
routes:
  - type: rewrite
    source: /*
    destination: /
